packages:
  - 'packages/*'

catalog:
  '@eslint/js': ^10.0.1
  '@vitest/coverage-v8': ^4.1.5
  '@vitest/ui': ^4.1.5
  eslint: ^10.3.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react-hooks: ^7.1.1
  eslint-plugin-react-refresh: ^0.5.2
  globals: ^17.6.0
  prettier: ^3.8.3
  stylelint: ^17.9.1
  stylelint-config-standard: ^40.0.0
  typescript: ^6.0.3
  vitest: ^4.1.5

onlyBuiltDependencies:
  - bcrypt
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild

strictPeerDependencies: false
