export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'backend',
        'frontend',
        'shared',
        'release',
        'security',
        'prisma',
        'deps',
        'docs',
        'ci',
        'config',
      ],
    ],
    'header-max-length': [2, 'always', 120],
    'body-max-line-length': [2, 'always', 120],
  },
};
